name: test
on: [push, pull_request]
jobs:
  # lint-js:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         cache: 'npm'
  #     - run: npm ci --no-audit
  #     - run: npm run lint:js
  lint-editorconfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
      - run: npm ci --no-audit
      - run: npm run lint:ec
  test:
    needs: [lint-editorconfig]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
      - run: npm ci --no-audit
      - run: npm test
      - uses: codecov/codecov-action@v1
